#!/bin/sh
# findfile

VERSION='1.0.0'

findfile_main() {
	trap _exit INT TERM

	e_args=16
	e_missing_app=17

	_require realpath

	scriptinv="$( basename "$0" )"
	scriptpath="$( realpath "$0" )"
	scriptname="$( basename "$scriptpath" )"

	while getopts hv opt
	do
		case $opt in
			h) cmd=help ;;
			v) cmd=version ;;
			*) _invalid_opt ;;
		esac
	done

	shift "$(( OPTIND - 1 ))"

	[ $# -lt 1 ] && [ -z "$cmd" ] && cmd="help"
	[ -z "$cmd" ] && cmd="process"

	case "$cmd" in
		help|process|version) "findfile_$cmd" "$@" ;;
		*) _invalid_cmd ;;
	esac

	_exit
}

findfile_help() {
cat <<USAGE
$scriptname $VERSION

USAGE: $scriptinv [-hv] <pattern> [<find options>]

Quickly find a file by pattern in the current directory using ‘find’.

OPTIONS:

	-h        Show this help screen.
	-v        Show script name and version number.

USAGE
}

findfile_process() {
	_require find
	pattern="$1"
	shift
	find . -iname "*$pattern*" "$@"
}

findfile_version() {
	_echo "$scriptname $VERSION"
}

_echo() {
	echo "$@"
}

_error() {
	_echo "$@" >&2
}

_exit() {
	exit_code=$?
	exit $exit_code
}

_fatal() {
	exit_code="$1"
	shift
	_error "$@"
	exit "$exit_code"
}

_invalid_cmd() {
	_error "Invalid command: $cmd"
	_echo
	findfile_help
	exit $e_args
}

_invalid_opt() {
	_error "Invalid option: $opt"
	_echo
	findfile_help
	exit $e_args
}

_require() {
	missing_bin=0

	for bin in "$@"
	do
		if ! which "$bin" > /dev/null 2>&1
		then
			missing_bin=1
			_error "Required: $bin"
		fi
	done

	if [ $missing_bin -ne 0 ]
	then
		_fatal $e_missing_app "One or more executables or apps are missing."
	fi
}

findfile_main "$@"
